# Generated by Neurodocker and Reproenv.

FROM debian:buster-slim
ENV OS="Linux" \
    PATH="/opt/freesurfer-7.1.1-min/bin:/opt/freesurfer-7.1.1-min/fsfast/bin:/opt/freesurfer-7.1.1-min/tktools:/opt/freesurfer-7.1.1-min/mni/bin:$PATH" \
    FREESURFER_HOME="/opt/freesurfer-7.1.1-min" \
    FREESURFER="/opt/freesurfer-7.1.1-min" \
    SUBJECTS_DIR="/opt/freesurfer-7.1.1-min/subjects" \
    LOCAL_DIR="/opt/freesurfer-7.1.1-min/local" \
    FSFAST_HOME="/opt/freesurfer-7.1.1-min/fsfast" \
    FMRI_ANALYSIS_DIR="/opt/freesurfer-7.1.1-min/fsfast" \
    FUNCTIONALS_DIR="/opt/freesurfer-7.1.1-min/sessions" \
    FS_OVERRIDE="0" \
    FIX_VERTEX_AREA="" \
    FSF_OUTPUT_FORMAT="nii.gz# mni env requirements" \
    MINC_BIN_DIR="/opt/freesurfer-7.1.1-min/mni/bin" \
    MINC_LIB_DIR="/opt/freesurfer-7.1.1-min/mni/lib" \
    MNI_DIR="/opt/freesurfer-7.1.1-min/mni" \
    MNI_DATAPATH="/opt/freesurfer-7.1.1-min/mni/data" \
    MNI_PERL5LIB="/opt/freesurfer-7.1.1-min/mni/share/perl5" \
    PERL5LIB="/opt/freesurfer-7.1.1-min/mni/share/perl5"
RUN apt-get update -qq \
    && apt-get install -y -q --no-install-recommends \
           bc \
           ca-certificates \
           curl \
           libgomp1 \
           libxmu6 \
           libxt6 \
           perl \
           tcsh \
    && rm -rf /var/lib/apt/lists/* \
    && echo "Downloading FreeSurfer ..." \
    && mkdir -p /opt/freesurfer-7.1.1-min \
    && curl -fL https://dl.dropbox.com/s/c3earkfhhvdyuo4/freesurfer-7.1.1-min.tgz \
    | tar -xz -C /opt/freesurfer-7.1.1-min --owner root --group root --no-same-owner --strip-components 1 \
         --exclude='average/mult-comp-cor' \
         --exclude='lib/cuda' \
         --exclude='lib/qt' \
         --exclude='subjects/V1_average' \
         --exclude='subjects/bert' \
         --exclude='subjects/cvs_avg35' \
         --exclude='subjects/cvs_avg35_inMNI152' \
         --exclude='subjects/fsaverage3' \
         --exclude='subjects/fsaverage4' \
         --exclude='subjects/fsaverage5' \
         --exclude='subjects/fsaverage6' \
         --exclude='subjects/fsaverage_sym' \
         --exclude='trctrain'

# Save specification to JSON.
RUN printf '{ \
  "pkg_manager": "apt", \
  "existing_users": [ \
    "root" \
  ], \
  "instructions": [ \
    { \
      "name": "from_", \
      "kwds": { \
        "base_image": "debian:buster-slim" \
      } \
    }, \
    { \
      "name": "env", \
      "kwds": { \
        "OS": "Linux", \
        "PATH": "/opt/freesurfer-7.1.1-min/bin:/opt/freesurfer-7.1.1-min/fsfast/bin:/opt/freesurfer-7.1.1-min/tktools:/opt/freesurfer-7.1.1-min/mni/bin:$PATH", \
        "FREESURFER_HOME": "/opt/freesurfer-7.1.1-min", \
        "FREESURFER": "/opt/freesurfer-7.1.1-min", \
        "SUBJECTS_DIR": "/opt/freesurfer-7.1.1-min/subjects", \
        "LOCAL_DIR": "/opt/freesurfer-7.1.1-min/local", \
        "FSFAST_HOME": "/opt/freesurfer-7.1.1-min/fsfast", \
        "FMRI_ANALYSIS_DIR": "/opt/freesurfer-7.1.1-min/fsfast", \
        "FUNCTIONALS_DIR": "/opt/freesurfer-7.1.1-min/sessions", \
        "FS_OVERRIDE": "0", \
        "FIX_VERTEX_AREA": "", \
        "FSF_OUTPUT_FORMAT": "nii.gz# mni env requirements", \
        "MINC_BIN_DIR": "/opt/freesurfer-7.1.1-min/mni/bin", \
        "MINC_LIB_DIR": "/opt/freesurfer-7.1.1-min/mni/lib", \
        "MNI_DIR": "/opt/freesurfer-7.1.1-min/mni", \
        "MNI_DATAPATH": "/opt/freesurfer-7.1.1-min/mni/data", \
        "MNI_PERL5LIB": "/opt/freesurfer-7.1.1-min/mni/share/perl5", \
        "PERL5LIB": "/opt/freesurfer-7.1.1-min/mni/share/perl5" \                 } \                                                                       }, \                                                                        { \                                                                           "name": "run", \                                                            "kwds": { \                                                                   "command": "apt-get update -qq\\napt-get install -y -q --no-install-recommends \\\\\\n    bc \\\\\\n    ca-certificates \\\\\\n    curl \\\\\\n    libgomp1 \\\\\\n    libxmu6 \\\\\\n    libxt6 \\\\\\n    perl \\\\\\n    tcsh\\nrm -rf /var/lib/apt/lists/*\\necho \\"Downloading FreeSurfer ...\\"\\nmkdir -p /opt/freesurfer-7.1.1-min\\ncurl -fL https://dl.dropbox.com/s/c3earkfhhvdyuo4/freesurfer-7.1.1-min.tgz \\\\\\n| tar -xz -C /opt/freesurfer-7.1.1-min --owner root --group root --no-same-owner --strip-components 1 \\\\\\n  --exclude='"'"'average/mult-comp-cor'"'"' \\\\\\n  --exclude='"'"'lib/cuda'"'"' \\\\\\n  --exclude='"'"'lib/qt'"'"' \\\\\\n  --exclude='"'"'subjects/V1_average'"'"' \\\\\\n  --exclude='"'"'subjects/bert'"'"' \\\\\\n  --exclude='"'"'subjects/cvs_avg35'"'"' \\\\\\n  --exclude='"'"'subjects/cvs_avg35_inMNI152'"'"' \\\\\\n  --exclude='"'"'subjects/fsaverage3'"'"' \\\\\\n  --exclude='"'"'subjects/fsaverage4'"'"' \\\\\\n  --exclude='"'"'subjects/fsaverage5'"'"' \\\\\\n  --exclude='"'"'subjects/fsaverage6'"'"' \\\\\\n  --exclude='"'"'subjects/fsaverage_sym'"'"' \\\\\\n  --exclude='"'"'trctrain'"'"'" \          } \                                                                       } \                                                                       ] \                                                                       }' > /.reproenv.json
        # End saving to specification to JSON.  